# - Find TinyXML2
# Find the native TinyXML2 includes and library
#
# TINYXML2_FOUND - True if TinyXML2 found.
# TINYXML2_INCLUDE_DIR - where to find tinyxml2.h, etc.
# TINYXML2_LIBRARIES - List of libraries when using TinyXML2.
#

IF( TINYXML2_INCLUDE_DIR )
# Already in cache, be silent
SET( TinyXML2_FIND_QUIETLY TRUE )
ENDIF( TINYXML2_INCLUDE_DIR )

FIND_PATH( TINYXML2_INCLUDE_DIR tinyxml2.h
PATH_SUFFIXES include/TinyXML2
PATHS
${EXT_LIBS})

FIND_LIBRARY( TINYXML2_DEBUG_LIBRARY
NAMES tinyxml2_d tinyxml2_debug
PATH_SUFFIXES lib 
PATHS
${EXT_LIBS_DIR})

FIND_LIBRARY( TINYXML2_RELEASE_LIBRARY
NAMES tinyxml2
PATH_SUFFIXES lib 
PATHS
${EXT_LIBS_DIR})

IF(TINYXML2_RELEASE_LIBRARY)
    IF(TINYXML2_DEBUG_LIBRARY)
        SET(TINYXML2_LIBRARY optimized "${TINYXML2_RELEASE_LIBRARY}" debug "${TINYXML2_DEBUG_LIBRARY}")
    ELSE()
        SET(TINYXML2_LIBRARY "${TINYXML2_RELEASE_LIBRARY}")        # Could add "general" keyword, but it is optional
    ENDIF()
ENDIF()


# handle the QUIETLY and REQUIRED arguments and set TINYXML2_FOUND to TRUE if
# all listed variables are TRUE
#INCLUDE( "FindPackageHandleStandardArgs" )
#FIND_PACKAGE_HANDLE_STANDARD_ARGS( "TinyXML2" DEFAULT_MSG TINYXML2_INCLUDE_DIR TINYXML2_LIBRARIES )

MARK_AS_ADVANCED( TINYXML2_INCLUDE_DIR TINYXML2_LIBRARY TINYXML2_RELEASE_LIBRARY TINYXML2_DEBUG_LIBRARY)

SET(TINYXML2_INCLUDE_DIR  "${TINYXML2_INCLUDE_DIR}")
SET(TINYXML2_LIBRARIES  "${TINYXML2_LIBRARY}")
